# Generated by Django 4.2.16 on 2024-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('numb', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
